version: "3.3"
services:
    encoder:
        image: navaapp.registry.com/nava-encoder
        networks:
            - net
            - traefik-public
        volumes:
            - /var/data/haji-encoder/.haji:/app/.haji
        depends_on:
            - mongodb
            - redis
        env_file: /var/data/config/haji-encoder/haji-encoder.env

        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
                - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
                - traefik.http.routers.encoder-https.rule=Host(`${ENCODER_DOMAIN?Variable not set}`)
                - traefik.http.routers.encoder-https.entrypoints=https
                - traefik.http.routers.encoder-http.rule=Host(`${ENCODER_DOMAIN?Variable not set}`)
                - traefik.http.routers.encoder-http.entrypoints=http
                - traefik.http.routers.encoder-http.middlewares=https-redirect
                - traefik.http.services.encoder.loadbalancer.server.port=3000
                - traefik.http.routers.encoder-https.tls=true
                - traefik.http.routers.encoder-https.tls.certresolver=le
            resources:
                limits:
                    # change base on your needs
                    cpus: '4.0' 
    redis:
        image: redis:alpine
        command: --requirepass ${REDIS_PASSWORD}
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT_NUMBER=6379
            - TZ=Asia/Tehran
        volumes:
            - /var/data/haji-encoder/redis:/data
        networks:
            - net
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - /var/data/haji-encoder/mongodb:/data/db
        networks:
            - net
        # ports:
        #     - "27017:27017"
networks:
    net:
        driver: overlay
        attachable: true
    traefik-public:
        external: true
